export const eslintBaseRules = {
  // possible Problems
  'default-param-last': 2,
  'no-prototype-builtins': 0,
  'no-loop-func': 2,
  'no-new-func': 2,
  'no-redeclare': 0,
  'no-script-url': 2,
  'no-unneeded-ternary': 2,
  'no-useless-computed-key': 2,
  'no-undef': 0,

  // suggestions
  'arrow-body-style': 2,
  camelcase: 1,
  curly: 2,
  'dot-notation': 2,
  'guard-for-in': 2,
  'no-alert': 2,
  'no-caller': 2,
  'no-div-regex': 2,
  'no-eval': 2,
  'no-extend-native': 2,
  'no-extra-bind': 2,
  'no-extra-label': 2,
  'no-implicit-coercion': 2,
  'no-labels': 2,
  'no-lone-blocks': 2,
  'no-multi-assign': 2,
  'no-multi-str': 2,
  'no-new-wrappers': 2,
  'no-octal-escape': 2,
  'no-proto': 2,
  'no-return-assign': 2,
  'no-sequences': 2,
  'no-useless-rename': 2,
  'no-useless-return': 2,
  'no-var': 2,
  'object-shorthand': [2, 'always'],
  'one-var': [2, 'never'],
  'operator-assignment': [2, 'always'],
  'prefer-arrow-callback': 2,
  'prefer-const': 2,
  'prefer-object-spread': 2,
  'prefer-template': 2,
  radix: 2,
  'require-await': 2,
  'unicode-bom': [2, 'never'],

  // deprecated
  'lines-between-class-members': [2, 'always'],
  'object-curly-newline': [
    2,
    {
      ObjectExpression: {
        multiline: true,
        minProperties: 2,
      },
      ImportDeclaration: 'never',
      ExportDeclaration: 'never',
    },
  ],
  'object-property-newline': [2, { allowAllPropertiesOnSameLine: false }],

  // eslint-plugin-import
  'import/no-empty-named-blocks': 'error',
  'import/no-import-module-exports': 'off',
  'import/no-absolute-path': 'error',
  'import/no-useless-path-segments': 'error',
  'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
  'import/first': 'error',
  'import/newline-after-import': 'error',
  'import/no-duplicates': 'error',
  'no-namespace': 'off',
  'import/order': 'off',
};
