export const prettier = {
  printWidth: 240,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'all',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  endOfLine: 'lf',
  embeddedLanguageFormatting: 'auto',
  singleAttributePerLine: true,
  plugins: [require.resolve('prettier-plugin-packagejson')],
  overrides: [
    {
      files: ['*.css', '*.less', '*.scss', '*.sass'],
      options: { singleQuote: false },
    },
  ],
};
